base: Screen Stabilization [1/2]
crdroidandroid/android_frameworks_base pull request #381
Opened 2020-03-15 15:00 UTC by Mustang-ssc

* New Settings menu integrated into QS itself(long click)
* Thanks to @SuperDroidBond for keeping this alive till Pie

Change-Id: Ibccb8d78d79938f42241ea3690ea66c3aace89ea
Signed-off-by: rituj <ritujbeniwal@gmail.com>
Signed-off-by: Mustang-ssc <mustangssc@protonmail.ch>

2020-03-15 19:46 UTC, gwolf2u commented
please correct PR by force pushing only https://github.com/crdroidandroid/android_frameworks_base/pull/381/commits/ab554f34f04eab4090a79da2acf8e61e62738940

2020-03-16 12:00 UTC, Mustang-ssc commented
> please correct PR by force pushing only [ab554f3](https://github.com/crdroidandroid/android_frameworks_base/commit/ab554f34f04eab4090a79da2acf8e61e62738940)

Now should be ok

2020-03-16 17:55 UTC, gwolf2u reviewed
@neobuddy89 should we keep current options or implement it in some setting under crDroid Settings?

2020-03-19 18:12 UTC, gwolf2u requested changes

2020-03-19 18:12 UTC, gwolf2u commented on packages/SystemUI/src/com/android/systemui/qs/tiles/ScreenStabilizationTile.java
> +        return MetricsEvent.BLISSIFY;
pay attention when cherry-picking

2020-03-19 18:12 UTC, gwolf2u commented
also test before PR

2020-03-19 18:53 UTC, gwolf2u commented
and also I see no QS tile 
how to make this work?
are there any dependencies ?

2020-03-19 19:10 UTC, SuperDroidBond commented
> 
> 
> and also I see no QS tile
> how to make this work?
> are there any dependencies ?

It's because it's not added in config under Custom Tiles Overlay.

2020-03-19 20:23 UTC, gwolf2u commented
> > and also I see no QS tile
> > how to make this work?
> > are there any dependencies ?
> 
> It's because it's not added in config under Custom Tiles Overlay.

Indeed
Missed that one 
Seems to work alright
Ty 👍

2020-03-19 20:23 UTC, closed without merging