base: Incall vibration options [1/3]
crdroidandroid/android_frameworks_base pull request #562
Opened 2021-01-11 17:51 UTC by Laker87

* allow setting vibration when call is connected
* allow setting vibration when call is disconnected
* allow setting vibration for call waiting
* this works with google and aosp dialer :)

Signed-off-by: Joey Huab <joey@evolution-x.org>

2021-01-11 17:53 UTC, gwolf2u commented
we already have FOD commits
clean base?

2021-01-11 18:04 UTC, Laker87 commented
> we already have FOD commits
> clean base?

Hm. Let me check why it happened.

2021-01-11 18:06 UTC, gwolf2u commented
just rebase
Pranav made some changes to fwb recently

2021-01-11 18:06 UTC, Laker87 commented
> just rebase
> Pranav made some changes to fwb recently

Oh, ok

2021-01-11 18:42 UTC, Laker87 commented
It seems OK now

2021-01-26 15:49 UTC, gwolf2u requested changes
commits are good
only small change needed here and we can merge (tested on my guacamole and beryllium)

2021-01-26 15:49 UTC, gwolf2u commented on core/java/android/provider/Settings.java
> +            PRIVATE_SETTINGS.add(VIBRATE_ON_CONNECT);
remove those - unsed

2021-01-26 16:11 UTC, Laker87 commented on core/java/android/provider/Settings.java
> +            PRIVATE_SETTINGS.add(VIBRATE_ON_CONNECT);
Done

2021-01-26 18:29 UTC, gwolf2u approved these changes

2021-01-26 18:29 UTC, merged