[SQUASH] base: Tint QS Tile with accent color [1/2]
crdroidandroid/android_frameworks_base pull request #570
Opened 2021-01-23 15:49 UTC by Laker87

* Tinted QS Tile stuffs (icon, background, label)
* Using bolder font

Adjust QS tile background and icon color

+ make qs tile icon smaller by 1dp
+ reduce qs tile vertical margin

SystemUI: Add a toggle for the new QS tint [1/2]

Co-authored-by: Stallix <joey@evolution-x.org>
Signed-off-by: Joey Huab <joey@evolution-x.org>

2021-01-23 21:45 UTC, neobuddy89 requested changes

2021-01-23 21:45 UTC, neobuddy89 commented on packages/SystemUI/src/com/android/systemui/qs/tileimpl/QSTileImpl.java
> +                    return Utils.getColorAttrDefaultColor(context, android.R.attr.textColorSecondary);
what's different here? if and else has same line of codes.

2021-01-23 21:45 UTC, neobuddy89 commented on packages/SystemUI/res/values/styles.xml
> +        <item name="android:fontFamily">@*android:string/config_headlineFontFamilyMedium</item>
why changing style?

2021-01-23 21:45 UTC, neobuddy89 commented on packages/SystemUI/res/values/dimens.xml
> +    <dimen name="qs_tile_margin_vertical">16dp</dimen>
why changing margin?

2021-01-23 21:45 UTC, neobuddy89 commented on core/java/android/provider/Settings.java
> +            PRIVATE_SETTINGS.add(QS_PANEL_BG_USE_NEW_TINT);
remove PRIVATE_SETTINGS

2021-01-23 21:45 UTC, neobuddy89 commented on packages/SystemUI/src/com/android/systemui/qs/tileimpl/QSTileBaseView.java
> +                Settings.System.QS_PANEL_BG_USE_NEW_TINT, 1, UserHandle.USER_CURRENT) == 1;
should not be enabled by default.

2021-01-24 15:59 UTC, Laker87 commented
Fixed

2021-02-01 19:53 UTC, neobuddy89 commented
Added.
https://github.com/crdroidandroid/android_frameworks_base/commit/bab41b028058e33f54dbd606e6f0e46b36f97b1d

2021-02-01 19:53 UTC, closed without merging