SystemUI: Add restart SystemUI in Advanced Reboot [1/2]
crdroidandroid/android_frameworks_base pull request #947
Opened 2023-02-06 07:33 UTC by awakened1712

Tested, working nicely.

2023-03-03 13:10 UTC, gwolf2u commented
please rebase

2023-03-03 15:31 UTC, awakened1712 commented
> please rebase

I'm on holiday. I'll do when I'm back next Monday

2023-03-03 18:06 UTC, ShevT commented
What is it for?

2023-03-03 18:20 UTC, gwolf2u commented
> What is it for?

restart SystemUI in reboot menu
there are some use cases for it I guess

2023-03-03 18:41 UTC, ShevT commented
> restart SystemUI in reboot menu there are some use cases for it I guess

I not see practical need

2023-03-03 18:43 UTC, gwolf2u commented
> > restart SystemUI in reboot menu there are some use cases for it I guess
> 
> I not see practical need

Example:
Some weird UI glitch that fixes itself after a reboot
This case simply restart systemui

2023-03-03 18:45 UTC, ShevT commented
> Example: Some weird UI glitch that fixes itself after a reboot This case simply restart systemui

Ok

2023-03-06 03:41 UTC, awakened1712 commented
> please rebase

Rebased

2023-03-12 18:41 UTC, neobuddy89 reviewed
@awakened1712 move string to cr_strings.xml in the end and not cm_strings.xml

2023-03-12 18:43 UTC, gwolf2u requested changes

2023-03-12 18:43 UTC, gwolf2u commented on packages/SystemUI/res/values/cm_strings.xml
> +    <string name="global_action_restart_systemui">SystemUI</string>
move string to cr_strings.xml

2023-03-13 03:38 UTC, awakened1712 commented
> @awakened1712 move string to cr_strings.xml in the end and not cm_strings.xml

Done

2023-03-13 10:25 UTC, ShevT commented
[ic_restart_systemui.xml](https://github.com/crdroidandroid/android_frameworks_base/pull/947/commits/da8472d988c1e84d80190f72ee4fb808147ec2be#diff-4a31dcdb5b23836530469ac888bc6a8f1802900c3f4fd1b589dae58ecd832f94) no newline at end of file.

2023-03-13 10:53 UTC, awakened1712 commented
> [ic_restart_systemui.xml](https://github.com/crdroidandroid/android_frameworks_base/pull/947/commits/da8472d988c1e84d80190f72ee4fb808147ec2be#diff-4a31dcdb5b23836530469ac888bc6a8f1802900c3f4fd1b589dae58ecd832f94) no newline at end of file.

Added

2023-03-13 15:09 UTC, neobuddy89 approved these changes

2023-03-13 15:10 UTC, merged